name: Update Chocolatey

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git Tag'
        required: true

env:
  CHOCO_PATH: packaging/windows/chocolatey

defaults:
  run:
    shell: bash

jobs:
  chocolatey:
    name: Deploy to chocolatey.org
    runs-on: windows-latest
    if: github.repository == 'openhv/openhv'
    steps:
      - name: Download Installer
        run: |
          mkdir -p ${{ env.CHOCO_PATH }}/tools/
          curl -sSL "https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag }}/$filename" -o "${{ env.CHOCO_PATH }}/tools/OpenHV-${{ github.event.inputs.tag }}-x64.exe"

      - name: Set Version
        id: version
        run: |
          tag=${{ github.event.inputs.tag }}
          version="${tag:0:4}.${tag:4:2}.${tag:6:2}"
          echo "::set-output name=nuget::$version"
          curl -sSL "https://raw.githubusercontent.com/OpenHV/OpenHV/master/packaging/windows/chocolatey/openhv.nuspec" -o "${{ env.CHOCO_PATH }}/openhv.nuspec"
          sed -i "s/{VERSION}/${version}/g" "${{ env.CHOCO_PATH }}/openhv.nuspec"

      - name: Pack Release
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack ${{ env.CHOCO_PATH }}/openhv.nuspec --outputdirectory ${{ env.CHOCO_PATH }}

      - name: Upload Release
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push ${{ env.CHOCO_PATH }}/openhv.${{ steps.version.outputs.nuget }}.nupkg -s https://push.chocolatey.org/ -k ${{ secrets.CHOCO_KEY }}
